Algoritmo "EX2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var
// Seção de Declarações das variáveis 
nome : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Qual é o seu nome? -> ")
leia(nome)
escreva("Seja bem-vindo(a),",nome)

Fimalgoritmo